# Generated by Django 4.1.2 on 2022-10-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('senha1', models.CharField(max_length=100, verbose_name='Senha')),
                ('senha2', models.CharField(max_length=100, verbose_name='Confirma sua Senha')),
                ('peso', models.DecimalField(decimal_places=3, max_digits=3, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Altura')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Treino', models.CharField(max_length=15)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exerc.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=225)),
                ('repeticoes', models.PositiveIntegerField()),
                ('vezes_repeticoes', models.PositiveIntegerField()),
                ('pausa', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('carga', models.PositiveIntegerField(blank=True, null=True)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exerc.treino')),
            ],
        ),
    ]
