# Generated by Django 4.1 on 2022-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Treino_pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=225)),
                ('repeticoes', models.PositiveIntegerField()),
                ('vezes_repeticoes', models.PositiveIntegerField()),
                ('pausa', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('carga', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
